### ISSUE TITLE
history get sortorder private why?

### ISSUE THREAD

**Issue by yolo3a525** [0312birdzhang/Zabbix4j#2]
history get sortorder private why?
-------------------
public class SortOrder {
        private String sortfield;
        private String order;

        private SortOrder() {
        }

        public String getSortfield() {
            return sortfield;
        }

        public void setSortfield(String sortfield) {
            this.sortfield = sortfield;
        }
    }

pls tell me. how to sortorder  desc or asc.
thanks
mail:3684170@qq.com

**Comment by 0312birdzhang** [comment]
This seems a bug
This code was written by <code>Created by Suguru Yajima on 2014/05/02.</code>
I will fix it soon.

**Comment by 0312birdzhang** [comment]
fix it
You can use
```java
ZabbixApi zabbixApi = new ZabbixApi(SysConstant.ZBX_URL);
		try {
			zabbixApi.login(SysConstant.ZBX_USER, SysConstant.ZBX_PWD);
			HistoryGetRequest historyGetRequest = new HistoryGetRequest();
			HistoryGetRequest.Params params = historyGetRequest.getParams();
			List<String> sortOrders = new ArrayList<>();
			List<String> sortfield = new ArrayList<>();
			sortOrders.add("DESC");
			sortfield.add("clock");
			
			List<Integer> itemids = new ArrayList<>();
			itemids.add(25702);
			
			params.setSortorder(sortOrders);
			params.setSortfield(sortfield);
			params.setLimit(10);
			params.setItemids(itemids);
			
			HistoryGetResponse response = zabbixApi.history().get(historyGetRequest);
			for(HistoryObject historyObject:response.getResult()){
				System.out.println(historyObject.getClock() + " == "+historyObject.getValue());
			}
			
		} catch (ZabbixApiException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```
And the result is:
```
1493111765 == 204
1493111705 == 227
1493111645 == 194
1493111585 == 196
1493111525 == 199
1493111465 == 200
1493111405 == 235
1493111345 == 196
1493111285 == 195
1493111225 == 195

```

**Comment by 0312birdzhang** [comment]
可以从这里下载 https://github.com/0312birdzhang/Zabbix4j/releases/tag/0.1.9

PS. 看你邮箱应该是国人 😂 
原作者的代码应该是为了适应 <code>Order of sorting. If an array is passed, each value will be matched to the corresponding property given in the sortfield parameter.</code>

**Comment by yolo3a525** [comment]
你与原作者什么关系那?这个项目现在你在维护,我也在https://github.com/myaaaaa-chan/Zabbix4j 这里提了问题.但是没人搭理.  我后来改成自己组织代码来处理了,不用jar了. json自己来解析处理. 希望会越来越好.
感觉原作者有些功能没有做完

**Comment by 0312birdzhang** [comment]
@yolo3a525 没有关系，原作者已经联系不上了。现在我在维护这个，原作者打了个框架然后留了一些坑。
