### ISSUE TITLE
jar包冲突slf4j

### ISSUE THREAD

**Issue by redisviewer** [0312birdzhang/Zabbix4j#3]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/D:/tools/apache-maven/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/tools/apache-maven/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
Exception in thread "main" java.lang.IllegalArgumentException: LoggerFactory is not a Logback LoggerContext but Logback is on the classpath. Either remove Logback or the competing implementation (class org.slf4j.impl.SimpleLoggerFactory loaded from file:/D:/tools/apache-maven/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar). If you are using WebLogic you will need to add 'org.slf4j' to prefer-application-packages in WEB-INF/weblogic.xml: org.slf4j.impl.SimpleLoggerFactory
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:389)
	at org.springframework.util.Assert.isInstanceOf(Assert.java:327)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.getLoggerContext(LogbackLoggingSystem.java:274)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.beforeInitialize(LogbackLoggingSystem.java:98)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartingEvent(LoggingApplicationListener.java:230)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:209)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.sihua.tech.operation.OperationApp.main(OperationApp.java:13)

项目使用springboot ，请作者帮忙看看如何排除jar包

**Comment by 0312birdzhang** [comment]
试试这样行不行
```
<dependency>
    <groupId>com.github.0312birdzhang</groupId>
    <artifactId>Zabbix4j</artifactId>
    <version>0.1.9</version>
   <exclusions>
      <exclusion>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-log4j12</artifactId>
      </exclusion>
  </exclusions> 
</dependency>
```

**Comment by redisviewer** [comment]
<dependency>
			<groupId>com.github.0312birdzhang</groupId>
			<artifactId>Zabbix4j</artifactId>
			<version>0.1.9</version>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-simple</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**# 排除了slf4j-simple后，问题得到了解决。
但是项目也出现了很多警告日志，idea日志打印出来也丢失了springboot日志的样式**

14:08:04,471 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:08:04,472 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:08:04,472 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/D:/tools/apache-maven/repository/com/github/0312birdzhang/Zabbix4j/0.1.9/Zabbix4j-0.1.9.jar!/logback.xml]
14:08:04,480 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6ed3ccb2 - URL [jar:file:/D:/tools/apache-maven/repository/com/github/0312birdzhang/Zabbix4j/0.1.9/Zabbix4j-0.1.9.jar!/logback.xml] is not of type file
14:08:04,544 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:08:04,551 |-INFO in ch.qos.logback.core.joran.action.TimestampAction - Using current interpretation time, i.e. now, as time reference.
14:08:04,561 |-INFO in ch.qos.logback.core.joran.action.TimestampAction - Adding property to the context with key="byDate" and value="20170908" to the LOCAL scope
14:08:04,561 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:08:04,564 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT1]
14:08:04,594 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT1] - This appender no longer admits a layout as a sub-component, set an encoder instead.
14:08:04,594 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT1] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
14:08:04,594 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT1] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
14:08:04,594 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:08:04,596 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [DEBUG]
14:08:04,603 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@442987331 - Will use zip compression
14:08:04,605 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@442987331 - Will use the pattern /data/logs/history/debug.%d{yyyy-MM-dd} for the active file
14:08:04,608 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/data/logs/history/debug.%d{yyyy-MM-dd}.zip'.
14:08:04,608 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:08:04,612 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Sep 08 14:01:57 CST 2017
14:08:04,614 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:08:04,617 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUG] - Active log file name: /data/logs/debug.log
14:08:04,617 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[DEBUG] - File property is set to [/data/logs/debug.log]
14:08:04,619 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:08:04,619 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [INFO]
14:08:04,621 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@366873404 - Will use zip compression
14:08:04,621 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@366873404 - Will use the pattern /data/logs/history/info.%d{yyyy-MM-dd} for the active file
14:08:04,622 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/data/logs/history/info.%d{yyyy-MM-dd}.zip'.
14:08:04,622 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:08:04,623 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Sep 08 14:01:26 CST 2017
14:08:04,623 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:08:04,624 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[INFO] - Active log file name: /data/logs/info.log
14:08:04,624 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[INFO] - File property is set to [/data/logs/info.log]
14:08:04,624 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:08:04,624 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ERROR]
14:08:04,625 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1217467887 - Will use zip compression
14:08:04,625 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1217467887 - Will use the pattern /data/logs/history/error_%d{yyyy-MM-dd} for the active file
14:08:04,626 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/data/logs/history/error_%d{yyyy-MM-dd}.zip'.
14:08:04,626 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:08:04,627 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Sep 08 10:14:01 CST 2017
14:08:04,627 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:08:04,627 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - Active log file name: /data/logs/error.log
14:08:04,627 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ERROR] - File property is set to [/data/logs/error.log]
14:08:04,627 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
14:08:04,630 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_STDOUT1]
14:08:04,630 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT1] to ch.qos.logback.classic.AsyncAppender[ASYNC_STDOUT1]
14:08:04,630 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_STDOUT1] - Attaching appender named [STDOUT1] to AsyncAppender.
14:08:04,630 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_STDOUT1] - Setting discardingThreshold to 51
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_INFO]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [INFO] to ch.qos.logback.classic.AsyncAppender[ASYNC_INFO]
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_INFO] - Attaching appender named [INFO] to AsyncAppender.
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_INFO] - Setting discardingThreshold to 51
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_ERROR]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to ch.qos.logback.classic.AsyncAppender[ASYNC_ERROR]
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_ERROR] - Attaching appender named [ERROR] to AsyncAppender.
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_ERROR] - Setting discardingThreshold to 51
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC_DEBUG]
14:08:04,631 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [DEBUG] to ch.qos.logback.classic.AsyncAppender[ASYNC_DEBUG]
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_DEBUG] - Attaching appender named [DEBUG] to AsyncAppender.
14:08:04,631 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC_DEBUG] - Setting discardingThreshold to 51
14:08:04,641 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:08:04,641 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [perf4jFileAppender]
14:08:04,642 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:08:04,645 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@945288723 - No compression will be used
14:08:04,646 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@945288723 - Will use the pattern /data/logs/perf4j.%d{yyyy-MM-dd}.log for the active file
14:08:04,646 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern '/data/logs/perf4j.%d{yyyy-MM-dd}.log'.
14:08:04,646 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
14:08:04,647 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Fri Sep 08 10:14:01 CST 2017
14:08:04,647 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[perf4jFileAppender] - Active log file name: /data/logs/perf4j.log
14:08:04,647 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[perf4jFileAppender] - File property is set to [/data/logs/perf4j.log]
14:08:04,648 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [org.perf4j.TimingLogger] to false
14:08:04,648 |-INFO in ch.qos.logback.classic.joran.action.LevelAction - org.perf4j.TimingLogger level set to INFO
14:08:04,648 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [perf4jFileAppender] to Logger[org.perf4j.TimingLogger]
14:08:04,648 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to INFO
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_STDOUT1] to Logger[org.springframework]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_INFO] to Logger[org.springframework]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.amazonaws] to INFO
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_STDOUT1] to Logger[com.amazonaws]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_INFO] to Logger[com.amazonaws]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.http] to INFO
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_STDOUT1] to Logger[org.apache.http]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_INFO] to Logger[org.apache.http]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.commons.configuration] to INFO
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_STDOUT1] to Logger[org.apache.commons.configuration]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_INFO] to Logger[org.apache.commons.configuration]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [freemarker] to INFO
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_STDOUT1] to Logger[freemarker]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_INFO] to Logger[freemarker]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to TRACE
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT1] to Logger[ROOT]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [INFO] to Logger[ROOT]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ERROR] to Logger[ROOT]
14:08:04,649 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC_DEBUG] to Logger[ROOT]
14:08:04,649 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:08:04,651 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@198b6731 - Registering current configuration as safe fallback point

**Comment by 0312birdzhang** [comment]
1.这些都是INFO级别的
2.自己配置一下logback.xml，应该就不显示了。具体怎么配置网上找找吧

**Comment by redisviewer** [comment]
感谢
